//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogByMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public int No { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> R1 { get; set; }
        public string R2 { get; set; }
        public Nullable<int> R3 { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
    }
}
